import Head from 'next/head'
import { Inter } from '@next/font/google'
import React, { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [calcGram, setCalcGram] = useState(0)
  const [coffeeGram, setCoffeeGram] = useState(0)
  const [ratio, setRatio] = useState(15)
  
  const handleChange = (event:any) => {
    setCoffeeGram(() => event.target.value)
  }
  
  const updateGram = () => {
    setCalcGram(coffeeGram*ratio)
  }

  const handleRatioChange = (event:any) => {
    setRatio(() => event.target.value)
  }

  return (
    <>
      <Head>
        <title>Coffee tools</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/coffee.png" />
      </Head>
      <header>
        <h1 className='text-4xl text-center bg-amber-800 text-white py-3 mb-4'>☕️ Coffee tools</h1>
      </header>
      <main>
        <div className='mx-4 p-2 text-gray-800 bg-slate-200 shadow-md'>
          <h1 className='text-2xl font-mono'>5回抽出の水量計算ツール</h1>
          <h2 className='text-lg'>コーヒの重さ (g) を入力 or 下のボタンから選択</h2>
          <input type="number" min="0" value={coffeeGram} onChange={handleChange} className='shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'/>
          <div className='flex'>
            <button onClick={()=>setCoffeeGram(() => 10)} className='bg-zinc-500 hover:bg-amber-600 text-white font-bold py-2 px-2 my-2 mr-2 rounded focus:outline-none focus:shadow-outline'>10g</button>
            <button onClick={()=>setCoffeeGram(() => 20)} className='bg-zinc-500 hover:bg-amber-600 text-white font-bold py-2 px-2 my-2 mr-2 rounded focus:outline-none focus:shadow-outline'>20g</button>
            <button onClick={()=>setCoffeeGram(() => 30)} className='bg-zinc-500 hover:bg-amber-600 text-white font-bold py-2 px-2 my-2 mr-2 rounded focus:outline-none focus:shadow-outline'>30g</button>
            <button onClick={()=>setCoffeeGram(() => 40)} className='bg-zinc-500 hover:bg-amber-600 text-white font-bold py-2 px-2 my-2 mr-2 rounded focus:outline-none focus:shadow-outline'>40g</button>
          </div>
          <button onClick={updateGram} className='bg-amber-600 hover:bg-amber-800 text-white text-lg font-bold py-2 px-2 mt-2 rounded focus:outline-none focus:shadow-outline'>計算</button>
          <p className='mt-2'>コーヒー:水 = 1:{ratio} の割合で水量を計算します。</p>
          <div className='text-xl mt-2'>
            <h2 className='text-2xl'>コーヒを除いた水量</h2>
            <p className='my-2 border-b-2 border-zinc-500'>全体の水量: {calcGram} g</p>
            <p>1ドリップ目: {calcGram*0.15} g</p>
            <p>2ドリップ目: {calcGram*0.3} g (+{calcGram*0.15}g)</p>
            <p>3ドリップ目: {calcGram*0.45} g (+{calcGram*0.15}g)</p>
            <p>4ドリップ目: {calcGram*0.7} g (+{calcGram*0.25}g)</p>
            <p>5ドリップ目: {calcGram} g (+{calcGram*0.3}g)</p>
          </div>
        </div>
        <div className='m-4 p-2 text-gray-800 bg-slate-100 shadow-md'>
          <h1 className='text-2xl font-mono'>🔧 設定</h1>
          <h2 className='text-lg'>コーヒの重さ (g)に対する水量の割合を設定</h2>
          <div className='flex'>
            <input type="range" step="1" min="1" max="20" value={ratio} onChange={handleRatioChange} className="accent-zinc-500 w-60"/>
            <p className='ml-4 text-lg'>{ratio}</p>
          </div>
        </div>
      </main>
      <footer>
        <h1 className=' border-y-8 border-amber-800 text-2xl text-center text-gray-800 py-3 mb-4'>🤎 enjoy your coffee time 🤎</h1>
      </footer>
    </>
  )
}