import Head from 'next/head'
import React, { useState } from 'react'
import {
  Button,
  Container,
  Divider,
  Group,
  NumberInput,
  Paper,
  Slider,
  Stack,
  Text,
  Title,
} from '@mantine/core'

const presetWeights = [15, 20, 25, 30, 40]

const brewSteps: Array<{ label: string; multiplier: number; increment?: number }> = [
  { label: '1ドリップ目', multiplier: 0.15 },
  { label: '2ドリップ目', multiplier: 0.3, increment: 0.15 },
  { label: '3ドリップ目', multiplier: 0.45, increment: 0.15 },
  { label: '4ドリップ目', multiplier: 0.7, increment: 0.25 },
  { label: '5ドリップ目', multiplier: 1, increment: 0.3 },
]

const formatWeight = (value: number) => (Number.isFinite(value) ? Math.round(value * 10) / 10 : 0)

export default function Home() {
  const [calcGram, setCalcGram] = useState(0)
  const [coffeeGram, setCoffeeGram] = useState(0)
  const [ratio, setRatio] = useState(15)

  const handleCoffeeChange = (value: number | string) => {
    const parsedValue = typeof value === 'number' ? value : Number(value)
    setCoffeeGram(Number.isFinite(parsedValue) ? parsedValue : 0)
  }

  const handlePresetSelect = (value: number) => {
    setCoffeeGram(value)
  }

  const handleRatioChange = (value: number) => {
    setRatio(Math.round(value))
  }

  const handleCalculationGram = () => {
    setCalcGram(coffeeGram * ratio)
  }

  const totalWater = calcGram

  return (
    <>
      <Head>
        <title>Coffee tools</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/coffee.png" />
      </Head>

      <Container size="sm" py="xl">
        <Stack gap="xl">
          <Stack gap="xs" align="center">
            <Title order={1} c="var(--mantine-color-coffee-7)">
              ☕️ Coffee tools
            </Title>
            <Text c="var(--mantine-color-coffee-6)">手軽にドリップレシピを計算しましょう。</Text>
          </Stack>

          <Paper withBorder shadow="md" radius="lg" p="xl" bg="var(--mantine-color-coffee-0)">
            <Stack gap="md">
              <Title order={2} c="var(--mantine-color-coffee-8)">
                5回抽出の水量計算ツール
              </Title>
              <Text size="sm">コーヒーの重さ (g) を入力するか、下のボタンから選択してください。</Text>

              <NumberInput
                label="コーヒーの重さ (g)"
                min={0}
                hideControls
                value={coffeeGram}
                onChange={handleCoffeeChange}
                placeholder="例: 20"
              />

              <Group gap="xs" wrap="wrap">
                {presetWeights.map((weight) => (
                  <Button
                    key={weight}
                    variant={coffeeGram === weight ? 'filled' : 'light'}
                    onClick={() => handlePresetSelect(weight)}
                    size="sm"
                  >
                    {weight} g
                  </Button>
                ))}
              </Group>

              <Button onClick={handleCalculationGram} disabled={coffeeGram <= 0} size="md">
                計算
              </Button>
              <Text size="sm" c="var(--mantine-color-coffee-6)">
                コーヒー:水 = 1:{ratio} の割合で水量を計算します。
              </Text>

              <Divider label="レシピ" labelPosition="center" />
              <Stack gap="sm">
                <Text fw={600}>全水量: {formatWeight(totalWater)} g</Text>
                {brewSteps.map(({ label, multiplier, increment }) => {
                  const amount = formatWeight(totalWater * multiplier)
                  const incrementText =
                    typeof increment === 'number'
                      ? ` (+${formatWeight(totalWater * increment)}g)`
                      : ''
                  return (
                    <Text key={label}>
                      {label}: {amount} g{incrementText}
                    </Text>
                  )
                })}
              </Stack>
            </Stack>
          </Paper>

          <Paper withBorder shadow="sm" radius="lg" p="xl" bg="var(--mantine-color-coffee-1)">
            <Stack gap="md">
              <Title order={2}>🔧 設定</Title>
              <Text size="sm">コーヒーの重さ (g) に対する水量の割合を設定してください。</Text>

              <Stack gap="xs">
                <Group justify="space-between" align="center">
                  <Text size="sm" fw={500}>
                    割合 (1:n)
                  </Text>
                  <Text fw={600}>{ratio}</Text>
                </Group>
                <Slider
                  min={1}
                  max={20}
                  step={1}
                  marks={[
                    { value: 5, label: '5' },
                    { value: 10, label: '10' },
                    { value: 15, label: '15' },
                    { value: 20, label: '20' },
                  ]}
                  value={ratio}
                  onChange={handleRatioChange}
                />
              </Stack>
            </Stack>
          </Paper>

          <Text ta="center" c="dimmed">
            🤎 enjoy your coffee time 🤎
          </Text>
        </Stack>
      </Container>
    </>
  )
}
